/**
 * MockGenerator - Mock 数据生成器
 *
 * 根据 OpenAPI 规范或 API 契约生成 Mock 数据和 MSW 风格的处理函数
 * 支持前端基于 Mock 数据独立开发
 */

class MockGenerator {
  /**
   * 生成 Mock 模块
   * @param {Object} openapiSpec - OpenAPI 规范对象
   * @param {Object} options - 生成选项
   * @param {string} options.basePath - 基础路径
   * @param {string} options.outputDir - 输出目录
   * @returns {Object} 包含 handlers.ts 和 data.ts 的内容
   */
  generateMockModule(openapiSpec, options = {}) {
    const { basePath = '/api', outputDir = 'src/mocks' } = options;

    const handlers = this._generateHandlers(openapiSpec, basePath);
    const data = this._generateMockData(openapiSpec);
    const apiClient = this._generateApiClient(openapiSpec, basePath);

    return {
      handlers,
      data,
      apiClient,
      outputDir,
      instructions: this._generateInstructions(openapiSpec)
    };
  }

  /**
   * 生成 MSW 风格的处理函数
   * @private
   */
  _generateHandlers(openapiSpec, basePath) {
    const handlers = [];
    const paths = openapiSpec.paths || {};

    for (const [path, methods] of Object.entries(paths)) {
      for (const [method, operation] of Object.entries(methods)) {
        if (['get', 'post', 'put', 'delete', 'patch'].includes(method.toLowerCase())) {
          const handler = this._generateHandler(path, method, operation, basePath);
          handlers.push(handler);
        }
      }
    }

    return this._formatHandlers(handlers);
  }

  /**
   * 生成单个处理函数
   * @private
   */
  _generateHandler(path, method, operation, basePath) {
    const operationId = operation.operationId || this._generateOperationId(path, method);
    const responseSchema = this._getResponseSchema(operation);
    const requestBody = operation.requestBody || null;

    return {
      operationId,
      method: method.toUpperCase(),
      path: `${basePath}${path}`,
      description: operation.description || operation.summary || '',
      responseSchema,
      requestBody,
      tags: operation.tags || []
    };
  }

  /**
   * 格式化处理函数为 TypeScript 代码
   * @private
   */
  _formatHandlers(handlers) {
    const lines = [
      `/**`,
      ` * MSW Mock Handlers`,
      ` * Generated by OrchestRouter MockGenerator`,
      ` * DO NOT EDIT MANUALLY`,
      ` */`,
      ``,
      `import { http, HttpResponse } from 'msw';`,
      `import { mockData } from './data';`,
      ``,
      `export const handlers = [`,
    ];

    for (const handler of handlers) {
      lines.push(`  // ${handler.description}`);
      lines.push(`  http.${handler.method.toLowerCase()}('${handler.path}', async ({ request }) => {`);
      lines.push(`    // TODO: Implement mock logic based on ${handler.operationId}`);

      if (handler.requestBody) {
        lines.push(`    const body = await request.json();`);
      }

      lines.push(`    return HttpResponse.json(mockData.${this._toCamelCase(handler.operationId)});`);
      lines.push(`  }),`);
      lines.push(``);
    }

    lines.push(`];`);
    return lines.join('\n');
  }

  /**
   * 生成 Mock 数据
   * @private
   */
  _generateMockData(openapiSpec) {
    const data = {};
    const paths = openapiSpec.paths || {};

    for (const [path, methods] of Object.entries(paths)) {
      for (const [method, operation] of Object.entries(methods)) {
        if (['get', 'post', 'put', 'delete', 'patch'].includes(method.toLowerCase())) {
          const operationId = operation.operationId || this._generateOperationId(path, method);
          data[this._toCamelCase(operationId)] = this._generateSampleResponse(operation);
        }
      }
    }

    return this._formatMockData(data);
  }

  /**
   * 格式化 Mock 数据为 TypeScript 代码
   * @private
   */
  _formatMockData(data) {
    const lines = [
      `/**`,
      ` * Mock Data`,
      ` * Generated by OrchestRouter MockGenerator`,
      ` * DO NOT EDIT MANUALLY`,
      ` */`,
      ``,
      `export const mockData = {`,
    ];

    for (const [key, value] of Object.entries(data)) {
      lines.push(`  ${key}: ${JSON.stringify(value, null, 2)},`);
      lines.push(``);
    }

    lines.push(`};`);
    return lines.join('\n');
  }

  /**
   * 生成 API Client（基于 Fetch）
   * @private
   */
  _generateApiClient(openapiSpec, basePath) {
    const lines = [
      `/**`,
      ` * API Client`,
      ` * Generated by OrchestRouter MockGenerator`,
      ` * Uses Mock data in development, real API in production`,
      ` */`,
      ``,
      `const API_BASE = '${basePath}';`,
      ``,
      `class ApiClient {`,
      `  private baseUrl: string;`,
      ``,
      `  constructor(baseUrl: string = API_BASE) {`,
      `    this.baseUrl = baseUrl;`,
      `  }`,
      ``,
      `  async request<T>(path: string, options?: RequestInit): Promise<T> {`,
      `    const response = await fetch(\`\${this.baseUrl}\${path}\`, {`,
      `      headers: {`,
      `        'Content-Type': 'application/json',`,
      `        ...options?.headers,`,
      `      },`,
      `      ...options,`,
      `    });`,
      `    if (!response.ok) {`,
      `      throw new Error(\`API Error: \${response.status}\`);`,
      `    }`,
      `    return response.json();`,
      `  }`,
      ``,
    ];

    // Generate method stubs based on OpenAPI spec
    const paths = openapiSpec.paths || {};
    const generatedMethods = new Set();

    for (const [path, methods] of Object.entries(paths)) {
      for (const [method, operation] of Object.entries(methods)) {
        if (['get', 'post', 'put', 'delete', 'patch'].includes(method.toLowerCase())) {
          const operationId = operation.operationId || this._generateOperationId(path, method);
          if (generatedMethods.has(operationId)) continue;
          generatedMethods.add(operationId);

          const methodName = this._toCamelCase(operationId);
          const paramNames = this._extractParamNames(path);
          const hasBody = !!operation.requestBody;

          lines.push(`  /**`);
          lines.push(`   * ${operation.summary || operationId}`);
          lines.push(`   */`);
          lines.push(`  async ${methodName}(${paramNames}${hasBody ? ', data?: unknown' : ''}): Promise<T> {`);
          lines.push(`    const url = \`\${this.baseUrl}${this._pathToTemplate(path)}\`;`);
          lines.push(`    return this.request<T>(url, {`);
          lines.push(`      method: '${method.toUpperCase()}',`);

          if (hasBody) {
            lines.push(`      body: JSON.stringify(data),`);
          }

          lines.push(`    });`);
          lines.push(`  }`);
          lines.push(``);
        }
      }
    }

    lines.push(`}`);
    lines.push(``);
    lines.push(`export const apiClient = new ApiClient();`);
    return lines.join('\n');
  }

  /**
   * 生成使用说明
   * @private
   */
  _generateInstructions(openapiSpec) {
    return `## Mock Service Layer 使用说明

### 文件结构
- \`src/mocks/handlers.ts\` - MSW HTTP 处理函数
- \`src/mocks/data.ts\` - Mock 数据
- \`src/mocks/api.ts\` - API 客户端

### 使用方法

#### 1. 安装 MSW
\`\`\`bash
npm install msw@latest --save-dev
npx msw init src/mocks --save
\`\`\`

#### 2. 在开发环境启用 Mock
\`\`\`typescript
// src/mocks/browser.ts
import { setupWorker } from 'msw/browser';
import { handlers } from './handlers';

export const worker = setupWorker(...handlers);
\`\`\`

#### 3. 在入口文件中启动
\`\`\`typescript
// main.tsx
if (process.env.NODE_ENV === 'development') {
  worker.start();
}
\`\`\`

#### 4. 使用 ApiClient
\`\`\`typescript
import { apiClient } from './mocks/api';

// 调用 API（开发环境使用 Mock，生产环境使用真实 API）
const products = await apiClient.getProducts();
\`\`\`

### 切换到真实 API
将 \`ApiClient\` 的 baseUrl 设置为真实 API 地址即可：
\`\`\`typescript
const realApiClient = new ApiClient('https://api.example.com');
\`\`\`
`;
  }

  /**
   * 获取响应 Schema
   * @private
   */
  _getResponseSchema(operation) {
    const responses = operation.responses || {};
    const successResponse = responses['200'] || responses['201'] || responses['default'];

    if (successResponse?.content?.['application/json']?.schema) {
      return successResponse.content['application/json'].schema;
    }

    return { type: 'object', description: 'No schema defined' };
  }

  /**
   * 生成示例响应数据
   * @private
   */
  _generateSampleResponse(operation) {
    const schema = this._getResponseSchema(operation);

    if (schema.example) {
      return schema.example;
    }

    if (schema.type === 'array' && schema.items) {
      return [this._generateFromSchema(schema.items)];
    }

    if (schema.type === 'object' && schema.properties) {
      const obj = {};
      for (const [key, prop] of Object.entries(schema.properties)) {
        obj[key] = this._generateFromSchema(prop);
      }
      return obj;
    }

    return this._getDefaultValue(schema.type);
  }

  /**
   * 从 Schema 生成示例值
   * @private
   */
  _generateFromSchema(schema) {
    if (schema.example) return schema.example;
    if (schema.default) return schema.default;

    switch (schema.type) {
      case 'string':
        if (schema.enum) return schema.enum[0];
        if (schema.format === 'date') return '2024-01-01';
        if (schema.format === 'date-time') return '2024-01-01T00:00:00Z';
        if (schema.format === 'email') return 'user@example.com';
        if (schema.format === 'uri') return 'https://example.com';
        return 'sample string';
      case 'number':
      case 'integer':
        return schema.minimum || 0;
      case 'boolean':
        return true;
      case 'array':
        return schema.items ? [this._generateFromSchema(schema.items)] : [];
      case 'object':
        if (schema.properties) {
          const obj = {};
          for (const [key, prop] of Object.entries(schema.properties)) {
            obj[key] = this._generateFromSchema(prop);
          }
          return obj;
        }
        return {};
      default:
        return null;
    }
  }

  /**
   * 获取类型的默认值
   * @private
   */
  _getDefaultValue(type) {
    const defaults = {
      string: '""',
      number: 0,
      integer: 0,
      boolean: false,
      array: '[]',
      object: '{}'
    };
    return defaults[type] || 'null';
  }

  /**
   * 生成操作 ID
   * @private
   */
  _generateOperationId(path, method) {
    const cleanPath = path.replace(/[^a-zA-Z0-9]/g, '_');
    return `${method.toLowerCase()}_${cleanPath}`.replace(/^_+/, '');
  }

  /**
   * 转换为驼峰命名
   * @private
   */
  _toCamelCase(str) {
    return str.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
  }

  /**
   * 将路径转换为模板字符串
   * @private
   */
  _pathToTemplate(path) {
    return path.replace(/\{([^}]+)\}/g, '${$1}');
  }

  /**
   * 提取路径参数名
   * @private
   */
  _extractParamNames(path) {
    const params = [];
    const regex = /\{([^}]+)\}/g;
    let match;
    while ((match = regex.exec(path)) !== null) {
      params.push(match[1]);
    }
    return params.map(p => `${p}: string`).join(', ');
  }
}

module.exports = MockGenerator;
